services:
  - type: web
    name: bytewatch-stremio-addon
    runtime: node
    buildCommand: |
      npm install
      node -e "const puppeteer = require('puppeteer'); console.log(puppeteer.executablePath());"
    startCommand: |
      node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CHROME_PATH
        value: /opt/render/.cache/puppeteer/chrome/linux-137.0.7151.119/chrome-linux64/chrome
      - key: DISPLAY
        value: ":99"
    plan: free