services:
  - type: web
    name: bytewatch-stremio-addon
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    plan: free