services:
  - type: web
    name: bytewatch-stremio-addon
    runtime: node
    buildCommand: |
      apt-get update -qq
      apt-get install -y -qq wget gnupg2
      
      # Add Google Chrome repository
      wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
      echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list
      
      # Install Chrome
      apt-get update -qq
      apt-get install -y -qq google-chrome-stable xvfb
      
      # Install npm dependencies
      npm install
      
      # Verify Chrome installation
      google-chrome-stable --version
    startCommand: |
      node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CHROME_PATH
        value: /opt/render/.cache/puppeteer/chrome/linux-137.0.7151.119/chrome-linux64/chrome
      - key: DISPLAY
        value: ":99"
    plan: free