services:
  - type: web
    name: bytewatch-stremio-addon
    env: node
    buildCommand: |
      apt-get update
      apt-get install -y chromium
      npm install
      npx puppeteer browsers install chrome
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CHROME_PATH
        value: /usr/bin/chromium
    plan: free